'use strict';

const { createRecord, updateRecord, queryRecords } = require('./salesforce');

/**
 * Create a Campaign record in Salesforce linked to the journey.
 */
async function createCampaign(conn, journey) {
  const campaignData = {
    Name: journey.name,
    Type: 'Email',
    Status: 'Planned',
    StartDate: new Date().toISOString().split('T')[0],
    IsActive: true,
    Description: `Auto-generated by Journey Builder. Journey ID: ${journey.id}`,
    Heroku_Journey_Id__c: journey.id,
    Journey_Status__c: 'Active',
  };

  if (journey.canvas_state) {
    campaignData.Journey_Definition__c = JSON.stringify(journey.canvas_state);
  }

  const result = await createRecord(conn, 'Campaign', campaignData);

  if (!result.success) {
    throw new Error(`Failed to create Campaign: ${JSON.stringify(result.errors)}`);
  }

  return result.id;
}

/**
 * Update Campaign status (e.g., when journey is paused or completed).
 */
async function updateCampaignStatus(conn, campaignId, status) {
  return updateRecord(conn, 'Campaign', {
    Id: campaignId,
    Journey_Status__c: status,
    Status: status === 'Active' ? 'In Progress' : status === 'Completed' ? 'Completed' : 'Planned',
  });
}

/**
 * Populate Campaign Members from the journey segment.
 * Uses Bulk API 2.0 for large datasets.
 */
async function populateCampaignMembers(conn, campaignId, segmentObject, segmentFilter) {
  // Build SOQL from segment filter
  let whereClause = '';
  if (segmentFilter && segmentFilter.conditions && segmentFilter.conditions.length > 0) {
    const conditions = segmentFilter.conditions.map((c) => {
      const val = typeof c.value === 'string' ? `'${c.value}'` : c.value;
      return `${c.field} ${mapOperator(c.operator)} ${val}`;
    });
    whereClause = ` WHERE ${conditions.join(` ${segmentFilter.logic || 'AND'} `)}`;
  }

  const idField = segmentObject === 'Lead' ? 'LeadId' : 'ContactId';
  const soql = `SELECT Id FROM ${segmentObject}${whereClause}`;

  const records = await queryRecords(conn, soql);

  if (!records.length) {
    console.warn('[CampaignService] No records found for segment filter');
    return { count: 0 };
  }

  // Batch-insert CampaignMembers
  const memberRecords = records.map((r) => ({
    CampaignId: campaignId,
    [idField]: r.Id,
    Status: 'Sent',
  }));

  const BATCH_SIZE = 200;
  let insertedCount = 0;

  for (let i = 0; i < memberRecords.length; i += BATCH_SIZE) {
    const batch = memberRecords.slice(i, i + BATCH_SIZE);
    const results = await conn.sobject('CampaignMember').create(batch);
    const successful = Array.isArray(results)
      ? results.filter((r) => r.success).length
      : results.success ? 1 : 0;
    insertedCount += successful;
  }

  return { count: insertedCount, total: records.length };
}

function mapOperator(op) {
  const operators = {
    equals: '=',
    notEquals: '!=',
    greaterThan: '>',
    lessThan: '<',
    greaterOrEqual: '>=',
    lessOrEqual: '<=',
    contains: 'LIKE',
    in: 'IN',
  };
  return operators[op] || '=';
}

module.exports = {
  createCampaign,
  updateCampaignStatus,
  populateCampaignMembers,
};
