'use strict';

const { sanitizeApiName } = require('./templateService');

const API_VERSION = '62.0';

/**
 * Transform a React Flow canvas state (nodes + edges) into Salesforce Flow metadata XML.
 * This is the core translation engine of the Journey Builder.
 *
 * Supported node types:
 *   trigger (Segment/Schedule/APIEvent) → <start>
 *   email   → <actionCalls> emailSimple
 *   wait    → <waits> AlarmEvent
 *   split   → <decisions> random percentage
 *   condition → <decisions> field criteria
 *   update  → <recordUpdates>
 *   webhook → <actionCalls> apex (JourneyWebhookCallout)
 *   exit    → (no element — path terminates)
 */
function generateFlowXml(journey, nodes, edges, templateMap) {
  const flowApiName = sanitizeApiName(`JB_${journey.name.replace(/\s+/g, '_')}_${journey.id.slice(0, 8)}`);
  const sortedNodes = topologicalSort(nodes, edges);

  // Build connectivity map
  const outgoing = buildOutgoingMap(edges);
  const elements = [];
  const variables = [];
  const textTemplates = [];

  // Start element
  const triggerNode = sortedNodes.find((n) => n.node_type === 'trigger');
  const startTarget = getNextNodeRef(triggerNode?.id, outgoing, sortedNodes);

  let startXml = buildStartElement(triggerNode, startTarget);

  // Process each non-trigger node
  for (const node of sortedNodes) {
    if (node.node_type === 'trigger') continue;
    if (node.node_type === 'exit') continue; // exits are just path terminators

    const nodeRef = nodeToRef(node);
    const nextRef = getNextNodeRef(node.id, outgoing, sortedNodes);

    switch (node.node_type) {
      case 'email':
        elements.push(buildEmailElement(node, nodeRef, nextRef, templateMap, textTemplates));
        break;
      case 'wait':
        elements.push(buildWaitElement(node, nodeRef, nextRef));
        break;
      case 'condition':
        elements.push(buildConditionElement(node, nodeRef, outgoing, sortedNodes, variables));
        break;
      case 'split':
        elements.push(buildSplitElement(node, nodeRef, outgoing, sortedNodes));
        break;
      case 'update':
        elements.push(buildUpdateElement(node, nodeRef, nextRef));
        break;
      case 'webhook':
        elements.push(buildWebhookElement(node, nodeRef, nextRef));
        break;
      default:
        console.warn(`[FlowGenerator] Unknown node type: ${node.node_type}`);
    }
  }

  // Assemble full XML
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>${API_VERSION}</apiVersion>
    <processType>AutoLaunchedFlow</processType>
    <status>Draft</status>
    <label>${escapeXml(journey.name)}</label>
    <description>Auto-generated by Heroku Journey Builder. Journey ID: ${journey.id}</description>
${startXml}
${elements.join('\n')}
${textTemplates.join('\n')}
${variables.join('\n')}
</Flow>`;

  return { flowApiName, xml };
}

/**
 * Generate the package.xml for the deployment ZIP.
 */
function generatePackageXml(flowApiName) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>${flowApiName}</members>
        <name>Flow</name>
    </types>
    <version>${API_VERSION}</version>
</Package>`;
}

// ---------------------------------------------------------------------------
// Element builders
// ---------------------------------------------------------------------------

function buildStartElement(triggerNode, targetRef) {
  const config = triggerNode?.config || {};
  const triggerType = config.triggerType || 'PlatformEvent';
  const triggerObject = config.triggerObject || 'Journey_Entry__e';

  return `
    <start>
        <locationX>50</locationX>
        <locationY>0</locationY>
        <connector>
            <targetReference>${targetRef}</targetReference>
        </connector>
        <object>${triggerObject}</object>
        <triggerType>${triggerType}</triggerType>
    </start>`;
}

function buildEmailElement(node, ref, nextRef, templateMap, textTemplates) {
  const config = node.config || {};
  const templateInfo = templateMap?.[node.id];
  const bodyRef = `${ref}_Body`;

  // Add text template for email body
  textTemplates.push(`
    <textTemplates>
        <name>${bodyRef}</name>
        <isViewedAsPlainText>false</isViewedAsPlainText>
        <text>${escapeXml(config.htmlBody || '<p>Email content</p>')}</text>
    </textTemplates>`);

  const connector = nextRef
    ? `<connector><targetReference>${nextRef}</targetReference></connector>`
    : '';

  return `
    <actionCalls>
        <name>${ref}</name>
        <label>${escapeXml(config.name || 'Send Email')}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 134}</locationY>
        <actionName>emailSimple</actionName>
        <actionType>emailSimple</actionType>
        ${connector}
        <inputParameters>
            <name>emailAddresses</name>
            <value>
                <elementReference>$Record.Email__c</elementReference>
            </value>
        </inputParameters>
        <inputParameters>
            <name>emailSubject</name>
            <value>
                <stringValue>${escapeXml(config.subject || 'Journey Email')}</stringValue>
            </value>
        </inputParameters>
        <inputParameters>
            <name>emailBody</name>
            <value>
                <elementReference>${bodyRef}</elementReference>
            </value>
        </inputParameters>
    </actionCalls>`;
}

function buildWaitElement(node, ref, nextRef) {
  const config = node.config || {};
  const duration = config.duration || 1;
  const unit = config.unit || 'Days';

  const connector = nextRef
    ? `<defaultConnector><targetReference>${nextRef}</targetReference></defaultConnector>`
    : '';

  return `
    <waits>
        <name>${ref}</name>
        <label>${escapeXml(config.name || `Wait ${duration} ${unit}`)}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 300}</locationY>
        ${connector}
        <waitEvents>
            <name>${ref}_Event</name>
            <conditionLogic>and</conditionLogic>
            <connector>
                <targetReference>${nextRef || ref}</targetReference>
            </connector>
            <eventType>AlarmEvent</eventType>
            <inputParameters>
                <name>AlarmTime</name>
                <value>
                    <elementReference>$Flow.CurrentDateTime</elementReference>
                </value>
            </inputParameters>
            <inputParameters>
                <name>TimeOffset</name>
                <value>
                    <numberValue>${duration}</numberValue>
                </value>
            </inputParameters>
            <inputParameters>
                <name>TimeOffsetUnit</name>
                <value>
                    <stringValue>${unit}</stringValue>
                </value>
            </inputParameters>
        </waitEvents>
    </waits>`;
}

function buildConditionElement(node, ref, outgoing, allNodes, variables) {
  const config = node.config || {};
  const edges = outgoing[node.id] || [];

  // Find Yes/No paths
  const yesEdge = edges.find((e) => e.label === 'Yes' || e.label === 'true');
  const noEdge = edges.find((e) => e.label === 'No' || e.label === 'false' || !e.label || e !== yesEdge);

  const yesTarget = yesEdge ? nodeToRefById(yesEdge.target_node_id, allNodes) : null;
  const noTarget = noEdge ? nodeToRefById(noEdge.target_node_id, allNodes) : null;

  const field = config.field || 'EmailOpenedFlag';
  const operator = config.operator || 'EqualTo';
  const value = config.value ?? 'true';

  const defaultConnector = noTarget
    ? `<defaultConnector><targetReference>${noTarget}</targetReference></defaultConnector>`
    : '';

  const ruleConnector = yesTarget
    ? `<connector><targetReference>${yesTarget}</targetReference></connector>`
    : '';

  return `
    <decisions>
        <name>${ref}</name>
        <label>${escapeXml(config.name || 'Condition Check')}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 450}</locationY>
        ${defaultConnector}
        <defaultConnectorLabel>No</defaultConnectorLabel>
        <rules>
            <name>${ref}_Yes</name>
            <conditionLogic>and</conditionLogic>
            <conditions>
                <leftValueReference>${field}</leftValueReference>
                <operator>${operator}</operator>
                <rightValue>
                    <stringValue>${escapeXml(String(value))}</stringValue>
                </rightValue>
            </conditions>
            ${ruleConnector}
            <label>Yes</label>
        </rules>
    </decisions>`;
}

function buildSplitElement(node, ref, outgoing, allNodes) {
  const config = node.config || {};
  const edges = outgoing[node.id] || [];
  const paths = config.paths || [{ label: 'Path A', percentage: 50 }, { label: 'Path B', percentage: 50 }];

  // Map edges to paths
  const rules = paths.map((p, i) => {
    const edge = edges[i];
    const target = edge ? nodeToRefById(edge.target_node_id, allNodes) : null;
    const connector = target
      ? `<connector><targetReference>${target}</targetReference></connector>`
      : '';

    return `
        <rules>
            <name>${ref}_${sanitizeApiName(p.label)}</name>
            <conditionLogic>and</conditionLogic>
            <conditions>
                <leftValueReference>SplitRandom</leftValueReference>
                <operator>LessThanOrEqualTo</operator>
                <rightValue>
                    <numberValue>${p.percentage}</numberValue>
                </rightValue>
            </conditions>
            ${connector}
            <label>${escapeXml(p.label)} (${p.percentage}%)</label>
        </rules>`;
  });

  // Default path is last rule's target
  const lastEdge = edges[edges.length - 1];
  const defaultTarget = lastEdge ? nodeToRefById(lastEdge.target_node_id, allNodes) : null;
  const defaultConnector = defaultTarget
    ? `<defaultConnector><targetReference>${defaultTarget}</targetReference></defaultConnector>`
    : '';

  return `
    <decisions>
        <name>${ref}</name>
        <label>${escapeXml(config.name || 'A/B Split')}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 400}</locationY>
        ${defaultConnector}
        <defaultConnectorLabel>Default</defaultConnectorLabel>
${rules.join('\n')}
    </decisions>`;
}

function buildUpdateElement(node, ref, nextRef) {
  const config = node.config || {};
  const connector = nextRef
    ? `<connector><targetReference>${nextRef}</targetReference></connector>`
    : '';

  return `
    <recordUpdates>
        <name>${ref}</name>
        <label>${escapeXml(config.name || 'Update Record')}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 500}</locationY>
        ${connector}
        <object>${config.object || 'Contact'}</object>
        <inputAssignments>
            <field>${config.field || 'Status'}</field>
            <value>
                <stringValue>${escapeXml(config.value || '')}</stringValue>
            </value>
        </inputAssignments>
    </recordUpdates>`;
}

function buildWebhookElement(node, ref, nextRef) {
  const config = node.config || {};
  const connector = nextRef
    ? `<connector><targetReference>${nextRef}</targetReference></connector>`
    : '';

  return `
    <actionCalls>
        <name>${ref}</name>
        <label>${escapeXml(config.name || 'Webhook Call')}</label>
        <locationX>${node.position_x || 176}</locationX>
        <locationY>${node.position_y || 500}</locationY>
        <actionName>JourneyWebhookCallout</actionName>
        <actionType>apex</actionType>
        ${connector}
        <inputParameters>
            <name>url</name>
            <value>
                <stringValue>${escapeXml(config.url || '')}</stringValue>
            </value>
        </inputParameters>
        <inputParameters>
            <name>method</name>
            <value>
                <stringValue>${config.method || 'POST'}</stringValue>
            </value>
        </inputParameters>
        <inputParameters>
            <name>body</name>
            <value>
                <stringValue>${escapeXml(config.body || '{}')}</stringValue>
            </value>
        </inputParameters>
    </actionCalls>`;
}

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

function nodeToRef(node) {
  return sanitizeApiName(`${node.node_type}_${node.id.replace(/-/g, '').slice(0, 12)}`);
}

function nodeToRefById(nodeId, allNodes) {
  const node = allNodes.find((n) => n.id === nodeId);
  if (!node || node.node_type === 'exit') return null;
  return nodeToRef(node);
}

function getNextNodeRef(nodeId, outgoing, allNodes) {
  const edges = outgoing[nodeId];
  if (!edges || edges.length === 0) return null;
  return nodeToRefById(edges[0].target_node_id, allNodes);
}

function buildOutgoingMap(edges) {
  const map = {};
  for (const edge of edges) {
    if (!map[edge.source_node_id]) map[edge.source_node_id] = [];
    map[edge.source_node_id].push(edge);
  }
  return map;
}

/**
 * Simple topological sort using Kahn's algorithm.
 * Ensures nodes are processed in dependency order.
 */
function topologicalSort(nodes, edges) {
  const inDegree = {};
  const adjacency = {};

  for (const node of nodes) {
    inDegree[node.id] = 0;
    adjacency[node.id] = [];
  }

  for (const edge of edges) {
    adjacency[edge.source_node_id]?.push(edge.target_node_id);
    if (inDegree[edge.target_node_id] !== undefined) {
      inDegree[edge.target_node_id]++;
    }
  }

  const queue = nodes.filter((n) => inDegree[n.id] === 0);
  const sorted = [];

  while (queue.length > 0) {
    const node = queue.shift();
    sorted.push(node);

    for (const neighborId of adjacency[node.id] || []) {
      inDegree[neighborId]--;
      if (inDegree[neighborId] === 0) {
        const neighborNode = nodes.find((n) => n.id === neighborId);
        if (neighborNode) queue.push(neighborNode);
      }
    }
  }

  // Add any remaining nodes (for disconnected graphs)
  for (const node of nodes) {
    if (!sorted.includes(node)) sorted.push(node);
  }

  return sorted;
}

function escapeXml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

module.exports = {
  generateFlowXml,
  generatePackageXml,
  nodeToRef,
  escapeXml,
};
